name: ExpressAuthStarter Test 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org/'

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        path: ExpressAuthStarter

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test
